version: '3.8'

services:
  web:
    build: .
    expose:
      - "8000"

    volumes:
      - .:/app

    environment:
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq_service
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis_service
      - rabbitmq_service

  cron:

    build: .

    command: cron -f

    volumes:
      - .:/app
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web


  redis_service:
    image: redis:alpine
    command: redis-server --appendonly yes
  rabbitmq_service:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  worker:
    build: .
    command: python email_worker.py
    volumes:
      - .:/app
    environment:
      - RABBITMQ_HOST=rabbitmq_service
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq_service
